sudo: required

language: generic

services:
  - docker

bundler_args: --retry 10

before_install:
  - cp .env.example .env

install:
  - docker build --tag salad/next-portfolio .
  - docker run --detach --publish 3000:3000 salad/next-portfolio

script:
  - travis_retry curl --fail localhost:3000 &> /dev/null
