sudo: required

language: generic

services:
  - docker

before_install:
  - cp .env.example .env
  - docker build --tag salad/next-portfolio .
  - docker run --detach --publish 3000:3000 salad/next-portfolio

install:
  - sudo apt-get update
  - sudo apt-get install -y curl

script:
  - curl --fail --retry 10 --retry-connrefused localhost:3000 &> /dev/null
