sudo: required

language: generic

services:
  - docker

before_install:
  - cp .env.example .env

install:
  - docker build --tag salad/next-portfolio .

script:
  - docker run --detach --publish 3000:3000 salad/next-portfolio
  - |
    for i in {1..10}
      do
        curl --fail localhost:3000 &> /dev/null

        if [ $? = 0 ]
          then
            break;
          fi

        sleep 1
      done
