sudo: required

language: generic

services:
  - docker

before_install:
  - cp .env.example .env
  - docker build --tag salad/next-portfolio .
  - docker run --detach --publish 3000:3000 salad/next-portfolio

script:
  - for i in {1..10}; do ping -c 1 -w 1 localhost &> /dev/null; if [ $? -eq 0 ]; then break; fi; sleep 1; done
  - curl --fail localhost:3000
